---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk:operator:namespace-manager
  labels:
    app.kubernetes.io/name: {{ template "splunk-operator.name" . }}
    helm.sh/chart: {{ template "splunk-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
subjects:
- kind: ServiceAccount
  name: splunk-operator
roleRef:
  kind: Role
  name: splunk:operator:namespace-manager
  apiGroup: rbac.authorization.k8s.io
