---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.containerPort }}
      protocol: TCP
      name: web
  selector:
    app: {{ .Values.database.name }}
  #clusterIP: None
