{{- if .Values.node.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.node.serviceAccount.name }}
  labels:
    {{- include "aws-fsx-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else }}
  {{- $exists := (lookup "v1" "ServiceAccount" .Release.Namespace .Values.node.serviceAccount.name) }}
  {{- if not $exists }}
    {{- fail (printf "create serviceaccount %s/%s or set .node.serviceaccount.create true" .Release.Namespace .Values.node.serviceAccount.name) }}
  {{- end }}
{{- end }}
---
